model:
  channels: 32
  num_blocks: 7
  semantic_classes: 13
  instance_classes: 13
  sem2ins_classes: []
  semantic_only: False
  ignore_label: -100
  decoder_cfg:
    num_layer: 6
    num_query: 400
    num_class: 13
    in_channel: 32
    d_model: 256
    nhead: 8
    hidden_dim: 1024
    dropout: 0.0
    activation_fn: 'gelu'
    iter_pred: True
    attn_mask: True
  criterion_cfg:
    ignore_label: -100
    loss_weight: [0.5, 1.0, 1.0]
    cost_weight: [0.5, 1.0, 1.0]
    non_object_weight: 0.1
    num_classes: 13
  # grouping_cfg:
  #   score_thr: 0.2
  #   radius: 0.04
  #   mean_active: 300
  #   class_numpoint_mean: [1823, 7457, 6189, 7424, 34229, 1724, 5439,
  #                         6016, 39796, 5279, 5092, 12210, 10225]
  #   npoint_thr: 0.05  # absolute if class_numpoint == -1, relative if class_numpoint != -1
  #   ignore_classes: [0, 1]
  # instance_voxel_cfg:
  #   scale: 50
  #   spatial_shape: 20
  # train_cfg:
  #   max_proposal_num: 200
  #   pos_iou_thr: 0.5
  test_cfg:
    x4_split: True
    cls_score_thr: 0.001
    mask_score_thr: -0.5
    min_npoint: 100
    test_topk_per_scene: 100
  fixed_modules: []

data:
  train:
    type: 's3dis_spf'
    data_root: 'dataset/s3dis/preprocess'
    prefix: ['Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6']
    suffix: '_inst_nostuff.pth'
    repeat: 1
    training: True
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    type: 's3dis_spf'
    data_root: 'dataset/s3dis/preprocess'
    prefix: 'Area_5'
    suffix: '_inst_nostuff.pth'
    training: False
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000

dataloader:
  train:
    batch_size: 4
    num_workers: 8
  test:
    batch_size: 1
    num_workers: 0

optimizer:
  type: 'AdamW'
  lr: 0.0001
  weight_decay: 0.05

save_cfg:
  semantic: True
  offset: True
  instance: True

fp16: False
epochs: 512
step_epoch: 0
save_freq: 2
pretrain: 'checkpoints/softgroup_s3dis_spconv2.pth'
work_dir: ''
